export const categorias=[
    {
        id:1,
        nombre: 'Carpeta Legal',
        descripcion: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum architecto non ea, delectus, accusantium tenetur in modi aut quo sapiente, accusamus nesciunt nulla laborum voluptates expedita similique tempore pariatur amet?',
        contenido: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim vero qui molestias rem facilis tenetur, sapiente consequatur repudiandae, harum aperiam, ipsum animi hic sint? Commodi hic numquam in quaerat quia doloribus maiores ipsa quod consectetur. Numquam molestiae illum tempora architecto placeat facilis repudiandae doloremque non laboriosam possimus exercitationem magnam, deserunt voluptatem, sit nemo, itaque rem veritatis vitae eos id cum. Iste doloribus inventore iure dolorem alias tempore laboriosam? Nam, alias aperiam. Laboriosam et adipisci laudantium quaerat ad, id cum, molestiae modi exercitationem ut dolorem, sed hic consequuntur veritatis nihil. A maiores cupiditate consectetur soluta aperiam, voluptatum tempore vero laboriosam id doloremque adipisci ad facere veniam, vitae rem quaerat assumenda alias molestias laudantium. Dicta eveniet accusamus maxime architecto tempore sequi ducimus ipsa natus cumque. Dolor eius voluptatibus iste doloremque est dolorem. Eius quis quidem mollitia aliquam temporibus cupiditate at, ratione excepturi omnis, consequatur laboriosam maiores, laudantium deserunt. Earum porro amet repellendus minus pariatur, similique cum at, quos ut rem repudiandae cupiditate? Distinctio fuga perferendis dignissimos, beatae molestias assumenda quis eum, nisi ipsam placeat at, qui commodi? Esse ratione fuga recusandae quod neque illum ullam quo corporis quia! Et dignissimos velit omnis voluptatem saepe nulla repellendus id. Autem adipisci repudiandae minus minima accusantium quae, saepe alias odit, nulla dolore distinctio architecto molestias ab porro quidem corporis. Voluptate dolor, consequuntur esse ea odio, quo aperiam doloremque ab et molestias corporis asperiores repellat quia animi. Reiciendis et esse ipsum iste quas inventore veritatis fuga! Amet, nesciunt distinctio laudantium voluptatum veniam praesentium eveniet. Numquam, accusantium?`
    },    {
        id:2,
        nombre: 'Misión y visión',
        descripcion: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum architecto non ea, delectus, accusantium tenetur in modi aut quo sapiente, accusamus nesciunt nulla laborum voluptates expedita similique tempore pariatur amet?',
        contenido: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim vero qui molestias rem facilis tenetur, sapiente consequatur repudiandae, harum aperiam, ipsum animi hic sint? Commodi hic numquam in quaerat quia doloribus maiores ipsa quod consectetur. Numquam molestiae illum tempora architecto placeat facilis repudiandae doloremque non laboriosam possimus exercitationem magnam, deserunt voluptatem, sit nemo, itaque rem veritatis vitae eos id cum. Iste doloribus inventore iure dolorem alias tempore laboriosam? Nam, alias aperiam. Laboriosam et adipisci laudantium quaerat ad, id cum, molestiae modi exercitationem ut dolorem, sed hic consequuntur veritatis nihil. A maiores cupiditate consectetur soluta aperiam, voluptatum tempore vero laboriosam id doloremque adipisci ad facere veniam, vitae rem quaerat assumenda alias molestias laudantium. Dicta eveniet accusamus maxime architecto tempore sequi ducimus ipsa natus cumque. Dolor eius voluptatibus iste doloremque est dolorem. Eius quis quidem mollitia aliquam temporibus cupiditate at, ratione excepturi omnis, consequatur laboriosam maiores, laudantium deserunt. Earum porro amet repellendus minus pariatur, similique cum at, quos ut rem repudiandae cupiditate? Distinctio fuga perferendis dignissimos, beatae molestias assumenda quis eum, nisi ipsam placeat at, qui commodi? Esse ratione fuga recusandae quod neque illum ullam quo corporis quia! Et dignissimos velit omnis voluptatem saepe nulla repellendus id. Autem adipisci repudiandae minus minima accusantium quae, saepe alias odit, nulla dolore distinctio architecto molestias ab porro quidem corporis. Voluptate dolor, consequuntur esse ea odio, quo aperiam doloremque ab et molestias corporis asperiores repellat quia animi. Reiciendis et esse ipsum iste quas inventore veritatis fuga! Amet, nesciunt distinctio laudantium voluptatum veniam praesentium eveniet. Numquam, accusantium?`
    },    {
        id:3,
        nombre: 'Organigrama',
        descripcion: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum architecto non ea, delectus, accusantium tenetur in modi aut quo sapiente, accusamus nesciunt nulla laborum voluptates expedita similique tempore pariatur amet?',
        contenido: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim vero qui molestias rem facilis tenetur, sapiente consequatur repudiandae, harum aperiam, ipsum animi hic sint? Commodi hic numquam in quaerat quia doloribus maiores ipsa quod consectetur. Numquam molestiae illum tempora architecto placeat facilis repudiandae doloremque non laboriosam possimus exercitationem magnam, deserunt voluptatem, sit nemo, itaque rem veritatis vitae eos id cum. Iste doloribus inventore iure dolorem alias tempore laboriosam? Nam, alias aperiam. Laboriosam et adipisci laudantium quaerat ad, id cum, molestiae modi exercitationem ut dolorem, sed hic consequuntur veritatis nihil. A maiores cupiditate consectetur soluta aperiam, voluptatum tempore vero laboriosam id doloremque adipisci ad facere veniam, vitae rem quaerat assumenda alias molestias laudantium. Dicta eveniet accusamus maxime architecto tempore sequi ducimus ipsa natus cumque. Dolor eius voluptatibus iste doloremque est dolorem. Eius quis quidem mollitia aliquam temporibus cupiditate at, ratione excepturi omnis, consequatur laboriosam maiores, laudantium deserunt. Earum porro amet repellendus minus pariatur, similique cum at, quos ut rem repudiandae cupiditate? Distinctio fuga perferendis dignissimos, beatae molestias assumenda quis eum, nisi ipsam placeat at, qui commodi? Esse ratione fuga recusandae quod neque illum ullam quo corporis quia! Et dignissimos velit omnis voluptatem saepe nulla repellendus id. Autem adipisci repudiandae minus minima accusantium quae, saepe alias odit, nulla dolore distinctio architecto molestias ab porro quidem corporis. Voluptate dolor, consequuntur esse ea odio, quo aperiam doloremque ab et molestias corporis asperiores repellat quia animi. Reiciendis et esse ipsum iste quas inventore veritatis fuga! Amet, nesciunt distinctio laudantium voluptatum veniam praesentium eveniet. Numquam, accusantium?`
    },    {
        id:4,
        nombre: 'Estrategia Empresarial',
        descripcion: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum architecto non ea, delectus, accusantium tenetur in modi aut quo sapiente, accusamus nesciunt nulla laborum voluptates expedita similique tempore pariatur amet?',
        contenido: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim vero qui molestias rem facilis tenetur, sapiente consequatur repudiandae, harum aperiam, ipsum animi hic sint? Commodi hic numquam in quaerat quia doloribus maiores ipsa quod consectetur. Numquam molestiae illum tempora architecto placeat facilis repudiandae doloremque non laboriosam possimus exercitationem magnam, deserunt voluptatem, sit nemo, itaque rem veritatis vitae eos id cum. Iste doloribus inventore iure dolorem alias tempore laboriosam? Nam, alias aperiam. Laboriosam et adipisci laudantium quaerat ad, id cum, molestiae modi exercitationem ut dolorem, sed hic consequuntur veritatis nihil. A maiores cupiditate consectetur soluta aperiam, voluptatum tempore vero laboriosam id doloremque adipisci ad facere veniam, vitae rem quaerat assumenda alias molestias laudantium. Dicta eveniet accusamus maxime architecto tempore sequi ducimus ipsa natus cumque. Dolor eius voluptatibus iste doloremque est dolorem. Eius quis quidem mollitia aliquam temporibus cupiditate at, ratione excepturi omnis, consequatur laboriosam maiores, laudantium deserunt. Earum porro amet repellendus minus pariatur, similique cum at, quos ut rem repudiandae cupiditate? Distinctio fuga perferendis dignissimos, beatae molestias assumenda quis eum, nisi ipsam placeat at, qui commodi? Esse ratione fuga recusandae quod neque illum ullam quo corporis quia! Et dignissimos velit omnis voluptatem saepe nulla repellendus id. Autem adipisci repudiandae minus minima accusantium quae, saepe alias odit, nulla dolore distinctio architecto molestias ab porro quidem corporis. Voluptate dolor, consequuntur esse ea odio, quo aperiam doloremque ab et molestias corporis asperiores repellat quia animi. Reiciendis et esse ipsum iste quas inventore veritatis fuga! Amet, nesciunt distinctio laudantium voluptatum veniam praesentium eveniet. Numquam, accusantium?`
    },    {
        id:5,
        nombre: 'Manual de Funcionamiento Interno',
        descripcion: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum architecto non ea, delectus, accusantium tenetur in modi aut quo sapiente, accusamus nesciunt nulla laborum voluptates expedita similique tempore pariatur amet?',
        contenido: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim vero qui molestias rem facilis tenetur, sapiente consequatur repudiandae, harum aperiam, ipsum animi hic sint? Commodi hic numquam in quaerat quia doloribus maiores ipsa quod consectetur. Numquam molestiae illum tempora architecto placeat facilis repudiandae doloremque non laboriosam possimus exercitationem magnam, deserunt voluptatem, sit nemo, itaque rem veritatis vitae eos id cum. Iste doloribus inventore iure dolorem alias tempore laboriosam? Nam, alias aperiam. Laboriosam et adipisci laudantium quaerat ad, id cum, molestiae modi exercitationem ut dolorem, sed hic consequuntur veritatis nihil. A maiores cupiditate consectetur soluta aperiam, voluptatum tempore vero laboriosam id doloremque adipisci ad facere veniam, vitae rem quaerat assumenda alias molestias laudantium. Dicta eveniet accusamus maxime architecto tempore sequi ducimus ipsa natus cumque. Dolor eius voluptatibus iste doloremque est dolorem. Eius quis quidem mollitia aliquam temporibus cupiditate at, ratione excepturi omnis, consequatur laboriosam maiores, laudantium deserunt. Earum porro amet repellendus minus pariatur, similique cum at, quos ut rem repudiandae cupiditate? Distinctio fuga perferendis dignissimos, beatae molestias assumenda quis eum, nisi ipsam placeat at, qui commodi? Esse ratione fuga recusandae quod neque illum ullam quo corporis quia! Et dignissimos velit omnis voluptatem saepe nulla repellendus id. Autem adipisci repudiandae minus minima accusantium quae, saepe alias odit, nulla dolore distinctio architecto molestias ab porro quidem corporis. Voluptate dolor, consequuntur esse ea odio, quo aperiam doloremque ab et molestias corporis asperiores repellat quia animi. Reiciendis et esse ipsum iste quas inventore veritatis fuga! Amet, nesciunt distinctio laudantium voluptatum veniam praesentium eveniet. Numquam, accusantium?`
    },    {
        id:6,
        nombre: 'Manual de SIG',
        descripcion: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum architecto non ea, delectus, accusantium tenetur in modi aut quo sapiente, accusamus nesciunt nulla laborum voluptates expedita similique tempore pariatur amet?',
        contenido: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim vero qui molestias rem facilis tenetur, sapiente consequatur repudiandae, harum aperiam, ipsum animi hic sint? Commodi hic numquam in quaerat quia doloribus maiores ipsa quod consectetur. Numquam molestiae illum tempora architecto placeat facilis repudiandae doloremque non laboriosam possimus exercitationem magnam, deserunt voluptatem, sit nemo, itaque rem veritatis vitae eos id cum. Iste doloribus inventore iure dolorem alias tempore laboriosam? Nam, alias aperiam. Laboriosam et adipisci laudantium quaerat ad, id cum, molestiae modi exercitationem ut dolorem, sed hic consequuntur veritatis nihil. A maiores cupiditate consectetur soluta aperiam, voluptatum tempore vero laboriosam id doloremque adipisci ad facere veniam, vitae rem quaerat assumenda alias molestias laudantium. Dicta eveniet accusamus maxime architecto tempore sequi ducimus ipsa natus cumque. Dolor eius voluptatibus iste doloremque est dolorem. Eius quis quidem mollitia aliquam temporibus cupiditate at, ratione excepturi omnis, consequatur laboriosam maiores, laudantium deserunt. Earum porro amet repellendus minus pariatur, similique cum at, quos ut rem repudiandae cupiditate? Distinctio fuga perferendis dignissimos, beatae molestias assumenda quis eum, nisi ipsam placeat at, qui commodi? Esse ratione fuga recusandae quod neque illum ullam quo corporis quia! Et dignissimos velit omnis voluptatem saepe nulla repellendus id. Autem adipisci repudiandae minus minima accusantium quae, saepe alias odit, nulla dolore distinctio architecto molestias ab porro quidem corporis. Voluptate dolor, consequuntur esse ea odio, quo aperiam doloremque ab et molestias corporis asperiores repellat quia animi. Reiciendis et esse ipsum iste quas inventore veritatis fuga! Amet, nesciunt distinctio laudantium voluptatum veniam praesentium eveniet. Numquam, accusantium?`
    },    {
        id:7,
        nombre: 'Planificación',
        descripcion: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum architecto non ea, delectus, accusantium tenetur in modi aut quo sapiente, accusamus nesciunt nulla laborum voluptates expedita similique tempore pariatur amet?',
        contenido: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim vero qui molestias rem facilis tenetur, sapiente consequatur repudiandae, harum aperiam, ipsum animi hic sint? Commodi hic numquam in quaerat quia doloribus maiores ipsa quod consectetur. Numquam molestiae illum tempora architecto placeat facilis repudiandae doloremque non laboriosam possimus exercitationem magnam, deserunt voluptatem, sit nemo, itaque rem veritatis vitae eos id cum. Iste doloribus inventore iure dolorem alias tempore laboriosam? Nam, alias aperiam. Laboriosam et adipisci laudantium quaerat ad, id cum, molestiae modi exercitationem ut dolorem, sed hic consequuntur veritatis nihil. A maiores cupiditate consectetur soluta aperiam, voluptatum tempore vero laboriosam id doloremque adipisci ad facere veniam, vitae rem quaerat assumenda alias molestias laudantium. Dicta eveniet accusamus maxime architecto tempore sequi ducimus ipsa natus cumque. Dolor eius voluptatibus iste doloremque est dolorem. Eius quis quidem mollitia aliquam temporibus cupiditate at, ratione excepturi omnis, consequatur laboriosam maiores, laudantium deserunt. Earum porro amet repellendus minus pariatur, similique cum at, quos ut rem repudiandae cupiditate? Distinctio fuga perferendis dignissimos, beatae molestias assumenda quis eum, nisi ipsam placeat at, qui commodi? Esse ratione fuga recusandae quod neque illum ullam quo corporis quia! Et dignissimos velit omnis voluptatem saepe nulla repellendus id. Autem adipisci repudiandae minus minima accusantium quae, saepe alias odit, nulla dolore distinctio architecto molestias ab porro quidem corporis. Voluptate dolor, consequuntur esse ea odio, quo aperiam doloremque ab et molestias corporis asperiores repellat quia animi. Reiciendis et esse ipsum iste quas inventore veritatis fuga! Amet, nesciunt distinctio laudantium voluptatum veniam praesentium eveniet. Numquam, accusantium?`
    },    {
        id:8,
        nombre: 'Objetivo de Trabajo',
        descripcion: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum architecto non ea, delectus, accusantium tenetur in modi aut quo sapiente, accusamus nesciunt nulla laborum voluptates expedita similique tempore pariatur amet?',
        contenido: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim vero qui molestias rem facilis tenetur, sapiente consequatur repudiandae, harum aperiam, ipsum animi hic sint? Commodi hic numquam in quaerat quia doloribus maiores ipsa quod consectetur. Numquam molestiae illum tempora architecto placeat facilis repudiandae doloremque non laboriosam possimus exercitationem magnam, deserunt voluptatem, sit nemo, itaque rem veritatis vitae eos id cum. Iste doloribus inventore iure dolorem alias tempore laboriosam? Nam, alias aperiam. Laboriosam et adipisci laudantium quaerat ad, id cum, molestiae modi exercitationem ut dolorem, sed hic consequuntur veritatis nihil. A maiores cupiditate consectetur soluta aperiam, voluptatum tempore vero laboriosam id doloremque adipisci ad facere veniam, vitae rem quaerat assumenda alias molestias laudantium. Dicta eveniet accusamus maxime architecto tempore sequi ducimus ipsa natus cumque. Dolor eius voluptatibus iste doloremque est dolorem. Eius quis quidem mollitia aliquam temporibus cupiditate at, ratione excepturi omnis, consequatur laboriosam maiores, laudantium deserunt. Earum porro amet repellendus minus pariatur, similique cum at, quos ut rem repudiandae cupiditate? Distinctio fuga perferendis dignissimos, beatae molestias assumenda quis eum, nisi ipsam placeat at, qui commodi? Esse ratione fuga recusandae quod neque illum ullam quo corporis quia! Et dignissimos velit omnis voluptatem saepe nulla repellendus id. Autem adipisci repudiandae minus minima accusantium quae, saepe alias odit, nulla dolore distinctio architecto molestias ab porro quidem corporis. Voluptate dolor, consequuntur esse ea odio, quo aperiam doloremque ab et molestias corporis asperiores repellat quia animi. Reiciendis et esse ipsum iste quas inventore veritatis fuga! Amet, nesciunt distinctio laudantium voluptatum veniam praesentium eveniet. Numquam, accusantium?`
    },    {
        id:9,
        nombre: 'Información documental Interna',
        descripcion: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum architecto non ea, delectus, accusantium tenetur in modi aut quo sapiente, accusamus nesciunt nulla laborum voluptates expedita similique tempore pariatur amet?',
        contenido: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim vero qui molestias rem facilis tenetur, sapiente consequatur repudiandae, harum aperiam, ipsum animi hic sint? Commodi hic numquam in quaerat quia doloribus maiores ipsa quod consectetur. Numquam molestiae illum tempora architecto placeat facilis repudiandae doloremque non laboriosam possimus exercitationem magnam, deserunt voluptatem, sit nemo, itaque rem veritatis vitae eos id cum. Iste doloribus inventore iure dolorem alias tempore laboriosam? Nam, alias aperiam. Laboriosam et adipisci laudantium quaerat ad, id cum, molestiae modi exercitationem ut dolorem, sed hic consequuntur veritatis nihil. A maiores cupiditate consectetur soluta aperiam, voluptatum tempore vero laboriosam id doloremque adipisci ad facere veniam, vitae rem quaerat assumenda alias molestias laudantium. Dicta eveniet accusamus maxime architecto tempore sequi ducimus ipsa natus cumque. Dolor eius voluptatibus iste doloremque est dolorem. Eius quis quidem mollitia aliquam temporibus cupiditate at, ratione excepturi omnis, consequatur laboriosam maiores, laudantium deserunt. Earum porro amet repellendus minus pariatur, similique cum at, quos ut rem repudiandae cupiditate? Distinctio fuga perferendis dignissimos, beatae molestias assumenda quis eum, nisi ipsam placeat at, qui commodi? Esse ratione fuga recusandae quod neque illum ullam quo corporis quia! Et dignissimos velit omnis voluptatem saepe nulla repellendus id. Autem adipisci repudiandae minus minima accusantium quae, saepe alias odit, nulla dolore distinctio architecto molestias ab porro quidem corporis. Voluptate dolor, consequuntur esse ea odio, quo aperiam doloremque ab et molestias corporis asperiores repellat quia animi. Reiciendis et esse ipsum iste quas inventore veritatis fuga! Amet, nesciunt distinctio laudantium voluptatum veniam praesentium eveniet. Numquam, accusantium?`
    },    {
        id:10,
        nombre: 'Requisitos Legales',
        descripcion: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum architecto non ea, delectus, accusantium tenetur in modi aut quo sapiente, accusamus nesciunt nulla laborum voluptates expedita similique tempore pariatur amet?',
        contenido: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim vero qui molestias rem facilis tenetur, sapiente consequatur repudiandae, harum aperiam, ipsum animi hic sint? Commodi hic numquam in quaerat quia doloribus maiores ipsa quod consectetur. Numquam molestiae illum tempora architecto placeat facilis repudiandae doloremque non laboriosam possimus exercitationem magnam, deserunt voluptatem, sit nemo, itaque rem veritatis vitae eos id cum. Iste doloribus inventore iure dolorem alias tempore laboriosam? Nam, alias aperiam. Laboriosam et adipisci laudantium quaerat ad, id cum, molestiae modi exercitationem ut dolorem, sed hic consequuntur veritatis nihil. A maiores cupiditate consectetur soluta aperiam, voluptatum tempore vero laboriosam id doloremque adipisci ad facere veniam, vitae rem quaerat assumenda alias molestias laudantium. Dicta eveniet accusamus maxime architecto tempore sequi ducimus ipsa natus cumque. Dolor eius voluptatibus iste doloremque est dolorem. Eius quis quidem mollitia aliquam temporibus cupiditate at, ratione excepturi omnis, consequatur laboriosam maiores, laudantium deserunt. Earum porro amet repellendus minus pariatur, similique cum at, quos ut rem repudiandae cupiditate? Distinctio fuga perferendis dignissimos, beatae molestias assumenda quis eum, nisi ipsam placeat at, qui commodi? Esse ratione fuga recusandae quod neque illum ullam quo corporis quia! Et dignissimos velit omnis voluptatem saepe nulla repellendus id. Autem adipisci repudiandae minus minima accusantium quae, saepe alias odit, nulla dolore distinctio architecto molestias ab porro quidem corporis. Voluptate dolor, consequuntur esse ea odio, quo aperiam doloremque ab et molestias corporis asperiores repellat quia animi. Reiciendis et esse ipsum iste quas inventore veritatis fuga! Amet, nesciunt distinctio laudantium voluptatum veniam praesentium eveniet. Numquam, accusantium?`
    },    {
        id:11,
        nombre: 'Otros Requisitos Aplicables',
        descripcion: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum architecto non ea, delectus, accusantium tenetur in modi aut quo sapiente, accusamus nesciunt nulla laborum voluptates expedita similique tempore pariatur amet?',
        contenido: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim vero qui molestias rem facilis tenetur, sapiente consequatur repudiandae, harum aperiam, ipsum animi hic sint? Commodi hic numquam in quaerat quia doloribus maiores ipsa quod consectetur. Numquam molestiae illum tempora architecto placeat facilis repudiandae doloremque non laboriosam possimus exercitationem magnam, deserunt voluptatem, sit nemo, itaque rem veritatis vitae eos id cum. Iste doloribus inventore iure dolorem alias tempore laboriosam? Nam, alias aperiam. Laboriosam et adipisci laudantium quaerat ad, id cum, molestiae modi exercitationem ut dolorem, sed hic consequuntur veritatis nihil. A maiores cupiditate consectetur soluta aperiam, voluptatum tempore vero laboriosam id doloremque adipisci ad facere veniam, vitae rem quaerat assumenda alias molestias laudantium. Dicta eveniet accusamus maxime architecto tempore sequi ducimus ipsa natus cumque. Dolor eius voluptatibus iste doloremque est dolorem. Eius quis quidem mollitia aliquam temporibus cupiditate at, ratione excepturi omnis, consequatur laboriosam maiores, laudantium deserunt. Earum porro amet repellendus minus pariatur, similique cum at, quos ut rem repudiandae cupiditate? Distinctio fuga perferendis dignissimos, beatae molestias assumenda quis eum, nisi ipsam placeat at, qui commodi? Esse ratione fuga recusandae quod neque illum ullam quo corporis quia! Et dignissimos velit omnis voluptatem saepe nulla repellendus id. Autem adipisci repudiandae minus minima accusantium quae, saepe alias odit, nulla dolore distinctio architecto molestias ab porro quidem corporis. Voluptate dolor, consequuntur esse ea odio, quo aperiam doloremque ab et molestias corporis asperiores repellat quia animi. Reiciendis et esse ipsum iste quas inventore veritatis fuga! Amet, nesciunt distinctio laudantium voluptatum veniam praesentium eveniet. Numquam, accusantium?`
    },    {
        id:12,
        nombre: 'Gestión de Riesgos',
        descripcion: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum architecto non ea, delectus, accusantium tenetur in modi aut quo sapiente, accusamus nesciunt nulla laborum voluptates expedita similique tempore pariatur amet?',
        contenido: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim vero qui molestias rem facilis tenetur, sapiente consequatur repudiandae, harum aperiam, ipsum animi hic sint? Commodi hic numquam in quaerat quia doloribus maiores ipsa quod consectetur. Numquam molestiae illum tempora architecto placeat facilis repudiandae doloremque non laboriosam possimus exercitationem magnam, deserunt voluptatem, sit nemo, itaque rem veritatis vitae eos id cum. Iste doloribus inventore iure dolorem alias tempore laboriosam? Nam, alias aperiam. Laboriosam et adipisci laudantium quaerat ad, id cum, molestiae modi exercitationem ut dolorem, sed hic consequuntur veritatis nihil. A maiores cupiditate consectetur soluta aperiam, voluptatum tempore vero laboriosam id doloremque adipisci ad facere veniam, vitae rem quaerat assumenda alias molestias laudantium. Dicta eveniet accusamus maxime architecto tempore sequi ducimus ipsa natus cumque. Dolor eius voluptatibus iste doloremque est dolorem. Eius quis quidem mollitia aliquam temporibus cupiditate at, ratione excepturi omnis, consequatur laboriosam maiores, laudantium deserunt. Earum porro amet repellendus minus pariatur, similique cum at, quos ut rem repudiandae cupiditate? Distinctio fuga perferendis dignissimos, beatae molestias assumenda quis eum, nisi ipsam placeat at, qui commodi? Esse ratione fuga recusandae quod neque illum ullam quo corporis quia! Et dignissimos velit omnis voluptatem saepe nulla repellendus id. Autem adipisci repudiandae minus minima accusantium quae, saepe alias odit, nulla dolore distinctio architecto molestias ab porro quidem corporis. Voluptate dolor, consequuntur esse ea odio, quo aperiam doloremque ab et molestias corporis asperiores repellat quia animi. Reiciendis et esse ipsum iste quas inventore veritatis fuga! Amet, nesciunt distinctio laudantium voluptatum veniam praesentium eveniet. Numquam, accusantium?`
    },    {
        id:13,
        nombre: 'Información y Comunicación',
        descripcion: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum architecto non ea, delectus, accusantium tenetur in modi aut quo sapiente, accusamus nesciunt nulla laborum voluptates expedita similique tempore pariatur amet?',
        contenido: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim vero qui molestias rem facilis tenetur, sapiente consequatur repudiandae, harum aperiam, ipsum animi hic sint? Commodi hic numquam in quaerat quia doloribus maiores ipsa quod consectetur. Numquam molestiae illum tempora architecto placeat facilis repudiandae doloremque non laboriosam possimus exercitationem magnam, deserunt voluptatem, sit nemo, itaque rem veritatis vitae eos id cum. Iste doloribus inventore iure dolorem alias tempore laboriosam? Nam, alias aperiam. Laboriosam et adipisci laudantium quaerat ad, id cum, molestiae modi exercitationem ut dolorem, sed hic consequuntur veritatis nihil. A maiores cupiditate consectetur soluta aperiam, voluptatum tempore vero laboriosam id doloremque adipisci ad facere veniam, vitae rem quaerat assumenda alias molestias laudantium. Dicta eveniet accusamus maxime architecto tempore sequi ducimus ipsa natus cumque. Dolor eius voluptatibus iste doloremque est dolorem. Eius quis quidem mollitia aliquam temporibus cupiditate at, ratione excepturi omnis, consequatur laboriosam maiores, laudantium deserunt. Earum porro amet repellendus minus pariatur, similique cum at, quos ut rem repudiandae cupiditate? Distinctio fuga perferendis dignissimos, beatae molestias assumenda quis eum, nisi ipsam placeat at, qui commodi? Esse ratione fuga recusandae quod neque illum ullam quo corporis quia! Et dignissimos velit omnis voluptatem saepe nulla repellendus id. Autem adipisci repudiandae minus minima accusantium quae, saepe alias odit, nulla dolore distinctio architecto molestias ab porro quidem corporis. Voluptate dolor, consequuntur esse ea odio, quo aperiam doloremque ab et molestias corporis asperiores repellat quia animi. Reiciendis et esse ipsum iste quas inventore veritatis fuga! Amet, nesciunt distinctio laudantium voluptatum veniam praesentium eveniet. Numquam, accusantium?`
    },    {
        id:14,
        nombre: 'Acciones de Control',
        descripcion: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum architecto non ea, delectus, accusantium tenetur in modi aut quo sapiente, accusamus nesciunt nulla laborum voluptates expedita similique tempore pariatur amet?',
        contenido: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim vero qui molestias rem facilis tenetur, sapiente consequatur repudiandae, harum aperiam, ipsum animi hic sint? Commodi hic numquam in quaerat quia doloribus maiores ipsa quod consectetur. Numquam molestiae illum tempora architecto placeat facilis repudiandae doloremque non laboriosam possimus exercitationem magnam, deserunt voluptatem, sit nemo, itaque rem veritatis vitae eos id cum. Iste doloribus inventore iure dolorem alias tempore laboriosam? Nam, alias aperiam. Laboriosam et adipisci laudantium quaerat ad, id cum, molestiae modi exercitationem ut dolorem, sed hic consequuntur veritatis nihil. A maiores cupiditate consectetur soluta aperiam, voluptatum tempore vero laboriosam id doloremque adipisci ad facere veniam, vitae rem quaerat assumenda alias molestias laudantium. Dicta eveniet accusamus maxime architecto tempore sequi ducimus ipsa natus cumque. Dolor eius voluptatibus iste doloremque est dolorem. Eius quis quidem mollitia aliquam temporibus cupiditate at, ratione excepturi omnis, consequatur laboriosam maiores, laudantium deserunt. Earum porro amet repellendus minus pariatur, similique cum at, quos ut rem repudiandae cupiditate? Distinctio fuga perferendis dignissimos, beatae molestias assumenda quis eum, nisi ipsam placeat at, qui commodi? Esse ratione fuga recusandae quod neque illum ullam quo corporis quia! Et dignissimos velit omnis voluptatem saepe nulla repellendus id. Autem adipisci repudiandae minus minima accusantium quae, saepe alias odit, nulla dolore distinctio architecto molestias ab porro quidem corporis. Voluptate dolor, consequuntur esse ea odio, quo aperiam doloremque ab et molestias corporis asperiores repellat quia animi. Reiciendis et esse ipsum iste quas inventore veritatis fuga! Amet, nesciunt distinctio laudantium voluptatum veniam praesentium eveniet. Numquam, accusantium?`
    },    {
        id:15,
        nombre: 'Informes de Revisión',
        descripcion: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum architecto non ea, delectus, accusantium tenetur in modi aut quo sapiente, accusamus nesciunt nulla laborum voluptates expedita similique tempore pariatur amet?',
        contenido: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim vero qui molestias rem facilis tenetur, sapiente consequatur repudiandae, harum aperiam, ipsum animi hic sint? Commodi hic numquam in quaerat quia doloribus maiores ipsa quod consectetur. Numquam molestiae illum tempora architecto placeat facilis repudiandae doloremque non laboriosam possimus exercitationem magnam, deserunt voluptatem, sit nemo, itaque rem veritatis vitae eos id cum. Iste doloribus inventore iure dolorem alias tempore laboriosam? Nam, alias aperiam. Laboriosam et adipisci laudantium quaerat ad, id cum, molestiae modi exercitationem ut dolorem, sed hic consequuntur veritatis nihil. A maiores cupiditate consectetur soluta aperiam, voluptatum tempore vero laboriosam id doloremque adipisci ad facere veniam, vitae rem quaerat assumenda alias molestias laudantium. Dicta eveniet accusamus maxime architecto tempore sequi ducimus ipsa natus cumque. Dolor eius voluptatibus iste doloremque est dolorem. Eius quis quidem mollitia aliquam temporibus cupiditate at, ratione excepturi omnis, consequatur laboriosam maiores, laudantium deserunt. Earum porro amet repellendus minus pariatur, similique cum at, quos ut rem repudiandae cupiditate? Distinctio fuga perferendis dignissimos, beatae molestias assumenda quis eum, nisi ipsam placeat at, qui commodi? Esse ratione fuga recusandae quod neque illum ullam quo corporis quia! Et dignissimos velit omnis voluptatem saepe nulla repellendus id. Autem adipisci repudiandae minus minima accusantium quae, saepe alias odit, nulla dolore distinctio architecto molestias ab porro quidem corporis. Voluptate dolor, consequuntur esse ea odio, quo aperiam doloremque ab et molestias corporis asperiores repellat quia animi. Reiciendis et esse ipsum iste quas inventore veritatis fuga! Amet, nesciunt distinctio laudantium voluptatum veniam praesentium eveniet. Numquam, accusantium?`
    },    {
        id:16,
        nombre: 'Gestión de innovación',
        descripcion: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum architecto non ea, delectus, accusantium tenetur in modi aut quo sapiente, accusamus nesciunt nulla laborum voluptates expedita similique tempore pariatur amet?',
        contenido: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim vero qui molestias rem facilis tenetur, sapiente consequatur repudiandae, harum aperiam, ipsum animi hic sint? Commodi hic numquam in quaerat quia doloribus maiores ipsa quod consectetur. Numquam molestiae illum tempora architecto placeat facilis repudiandae doloremque non laboriosam possimus exercitationem magnam, deserunt voluptatem, sit nemo, itaque rem veritatis vitae eos id cum. Iste doloribus inventore iure dolorem alias tempore laboriosam? Nam, alias aperiam. Laboriosam et adipisci laudantium quaerat ad, id cum, molestiae modi exercitationem ut dolorem, sed hic consequuntur veritatis nihil. A maiores cupiditate consectetur soluta aperiam, voluptatum tempore vero laboriosam id doloremque adipisci ad facere veniam, vitae rem quaerat assumenda alias molestias laudantium. Dicta eveniet accusamus maxime architecto tempore sequi ducimus ipsa natus cumque. Dolor eius voluptatibus iste doloremque est dolorem. Eius quis quidem mollitia aliquam temporibus cupiditate at, ratione excepturi omnis, consequatur laboriosam maiores, laudantium deserunt. Earum porro amet repellendus minus pariatur, similique cum at, quos ut rem repudiandae cupiditate? Distinctio fuga perferendis dignissimos, beatae molestias assumenda quis eum, nisi ipsam placeat at, qui commodi? Esse ratione fuga recusandae quod neque illum ullam quo corporis quia! Et dignissimos velit omnis voluptatem saepe nulla repellendus id. Autem adipisci repudiandae minus minima accusantium quae, saepe alias odit, nulla dolore distinctio architecto molestias ab porro quidem corporis. Voluptate dolor, consequuntur esse ea odio, quo aperiam doloremque ab et molestias corporis asperiores repellat quia animi. Reiciendis et esse ipsum iste quas inventore veritatis fuga! Amet, nesciunt distinctio laudantium voluptatum veniam praesentium eveniet. Numquam, accusantium?`
    },    {
        id:17,
        nombre: 'Mural',
        descripcion: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum architecto non ea, delectus, accusantium tenetur in modi aut quo sapiente, accusamus nesciunt nulla laborum voluptates expedita similique tempore pariatur amet?',
        contenido: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim vero qui molestias rem facilis tenetur, sapiente consequatur repudiandae, harum aperiam, ipsum animi hic sint? Commodi hic numquam in quaerat quia doloribus maiores ipsa quod consectetur. Numquam molestiae illum tempora architecto placeat facilis repudiandae doloremque non laboriosam possimus exercitationem magnam, deserunt voluptatem, sit nemo, itaque rem veritatis vitae eos id cum. Iste doloribus inventore iure dolorem alias tempore laboriosam? Nam, alias aperiam. Laboriosam et adipisci laudantium quaerat ad, id cum, molestiae modi exercitationem ut dolorem, sed hic consequuntur veritatis nihil. A maiores cupiditate consectetur soluta aperiam, voluptatum tempore vero laboriosam id doloremque adipisci ad facere veniam, vitae rem quaerat assumenda alias molestias laudantium. Dicta eveniet accusamus maxime architecto tempore sequi ducimus ipsa natus cumque. Dolor eius voluptatibus iste doloremque est dolorem. Eius quis quidem mollitia aliquam temporibus cupiditate at, ratione excepturi omnis, consequatur laboriosam maiores, laudantium deserunt. Earum porro amet repellendus minus pariatur, similique cum at, quos ut rem repudiandae cupiditate? Distinctio fuga perferendis dignissimos, beatae molestias assumenda quis eum, nisi ipsam placeat at, qui commodi? Esse ratione fuga recusandae quod neque illum ullam quo corporis quia! Et dignissimos velit omnis voluptatem saepe nulla repellendus id. Autem adipisci repudiandae minus minima accusantium quae, saepe alias odit, nulla dolore distinctio architecto molestias ab porro quidem corporis. Voluptate dolor, consequuntur esse ea odio, quo aperiam doloremque ab et molestias corporis asperiores repellat quia animi. Reiciendis et esse ipsum iste quas inventore veritatis fuga! Amet, nesciunt distinctio laudantium voluptatum veniam praesentium eveniet. Numquam, accusantium?`
    },    {
        id:18,
        nombre: 'Boletín Informativo',
        descripcion: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum architecto non ea, delectus, accusantium tenetur in modi aut quo sapiente, accusamus nesciunt nulla laborum voluptates expedita similique tempore pariatur amet?',
        contenido: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim vero qui molestias rem facilis tenetur, sapiente consequatur repudiandae, harum aperiam, ipsum animi hic sint? Commodi hic numquam in quaerat quia doloribus maiores ipsa quod consectetur. Numquam molestiae illum tempora architecto placeat facilis repudiandae doloremque non laboriosam possimus exercitationem magnam, deserunt voluptatem, sit nemo, itaque rem veritatis vitae eos id cum. Iste doloribus inventore iure dolorem alias tempore laboriosam? Nam, alias aperiam. Laboriosam et adipisci laudantium quaerat ad, id cum, molestiae modi exercitationem ut dolorem, sed hic consequuntur veritatis nihil. A maiores cupiditate consectetur soluta aperiam, voluptatum tempore vero laboriosam id doloremque adipisci ad facere veniam, vitae rem quaerat assumenda alias molestias laudantium. Dicta eveniet accusamus maxime architecto tempore sequi ducimus ipsa natus cumque. Dolor eius voluptatibus iste doloremque est dolorem. Eius quis quidem mollitia aliquam temporibus cupiditate at, ratione excepturi omnis, consequatur laboriosam maiores, laudantium deserunt. Earum porro amet repellendus minus pariatur, similique cum at, quos ut rem repudiandae cupiditate? Distinctio fuga perferendis dignissimos, beatae molestias assumenda quis eum, nisi ipsam placeat at, qui commodi? Esse ratione fuga recusandae quod neque illum ullam quo corporis quia! Et dignissimos velit omnis voluptatem saepe nulla repellendus id. Autem adipisci repudiandae minus minima accusantium quae, saepe alias odit, nulla dolore distinctio architecto molestias ab porro quidem corporis. Voluptate dolor, consequuntur esse ea odio, quo aperiam doloremque ab et molestias corporis asperiores repellat quia animi. Reiciendis et esse ipsum iste quas inventore veritatis fuga! Amet, nesciunt distinctio laudantium voluptatum veniam praesentium eveniet. Numquam, accusantium?`
    },
]